# PostgreSQL. Versions 9.3 and up are supported.
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: '@agendor00'

development:
  <<: *default
  database: ecommenrce_development
 
test:
  <<: *default
  database: ecommenrce_test

production:
  <<: *default
  database: ecommenrce_development
  username: ecoomenrce_galde
  password: <%= ENV["ECOOMENRCE_GALDE_DATABASE_PASSWORD"] %>
